USE [master]
GO

/****** Object:  Database [UserBanking]    Script Date: 8/8/2024 11:36:51 PM ******/
CREATE DATABASE [UserBanking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UserBanking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UserBanking.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UserBanking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UserBanking_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserBanking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserBanking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserBanking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserBanking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserBanking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserBanking] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserBanking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UserBanking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserBanking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserBanking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserBanking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserBanking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserBanking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserBanking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserBanking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserBanking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UserBanking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserBanking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserBanking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserBanking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserBanking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserBanking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UserBanking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserBanking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UserBanking] SET  MULTI_USER 
GO

ALTER DATABASE [UserBanking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserBanking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UserBanking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UserBanking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UserBanking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UserBanking] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UserBanking] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UserBanking] SET  READ_WRITE 
GO


